spring:
  config:
    import:
      - classpath:/application-secret.yml
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            scope: email
            redirect-uri: http://localhost:8080/auth/oauth/code
#            client-id: your-client-id
#            client-secret: your-client-secret
          kakao:
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: kakao
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/auth/oauth/code
#            client-id: your-client-id
#            client-secret: your-client-secret
          naver:
            authorization-grant-type: authorization_code
            scope:
            client-name: Naver
            redirect-uri: http://localhost:8080/auth/oauth/code
#            client-id: your-client-id
#            client-secret: your-client-secret
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


jwt:
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Refresh
  key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKXROG4n3srR2asr1BIhvcNAQEBBQADSwAwSAJBAKXROG4ROG4n3srR2asr1BIhvcNAQ