spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 577159361441-tdcsm80fn4rodt1m16r05qtb48cakrkp.apps.googleusercontent.com
            client-secret: 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
          kakao:
            client-id: 655f82c50a175820dccd0357df745c73
            client-secret: cNcJ77cP6IpBEts9E4DvtwtZ6yg0qTQm
          naver:
            client-id: TsAWqp4k3hCTbx9cHULL
            client-secret: 0dbYwMdrjo
